// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P011_IsTakip.DataAccess.Context;

#nullable disable

namespace P011_IsTakip.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230428115652_DepoYTNullable")]
    partial class DepoYTNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Ajanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NotTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Ajanda");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Depo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yetkili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Depo");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.DepoEnvanter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<float>("Agirlik")
                        .HasColumnType("real");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<float>("Boy")
                        .HasColumnType("real");

                    b.Property<int>("DepoId")
                        .HasColumnType("int");

                    b.Property<int>("DepoRafId")
                        .HasColumnType("int");

                    b.Property<float>("En")
                        .HasColumnType("real");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KalinlikId")
                        .HasColumnType("int");

                    b.Property<int>("MalzemeTipId")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.HasIndex("DepoRafId");

                    b.HasIndex("KalinlikId");

                    b.HasIndex("MalzemeTipId");

                    b.HasIndex("MusteriId");

                    b.ToTable("DepoEnvanter");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.DepoRaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DepoRaf");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.DurusTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DurusTip");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Is", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBitimindeBildir")
                        .HasColumnType("bit");

                    b.Property<string>("IsNotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsOnceligi")
                        .HasColumnType("int");

                    b.Property<bool>("Iscilik")
                        .HasColumnType("bit");

                    b.Property<int>("KalinlikId")
                        .HasColumnType("int");

                    b.Property<string>("MalzemeNotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MalzemeTipId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriSiparisNo")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("TeklifNo")
                        .HasColumnType("int");

                    b.Property<bool>("Teklifli")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Termin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KalinlikId");

                    b.HasIndex("MalzemeTipId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Is");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.IsDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("IsId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IsId")
                        .IsUnique();

                    b.ToTable("IsDosya");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Kalinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kalinlik");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MailBildirim")
                        .HasColumnType("bit");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("RolTanim")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId")
                        .IsUnique()
                        .HasFilter("[MusteriId] IS NOT NULL");

                    b.ToTable("Kullanici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ediz",
                            Aktif = true,
                            GuncellemeTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1156),
                            KullaniciKodu = "Ediz",
                            KullaniciSifre = "123",
                            MailBildirim = false,
                            OlusturanKullanici = "Ediz",
                            OlusturanKullaniciId = 1,
                            OlusturmaTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1149),
                            RolTanim = 0,
                            Silindi = false,
                            Soyad = "Hun"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Kemal",
                            Aktif = true,
                            GuncellemeTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1174),
                            KullaniciKodu = "Kemal",
                            KullaniciSifre = "1234",
                            MailBildirim = false,
                            OlusturanKullanici = "Kemal",
                            OlusturanKullaniciId = 2,
                            OlusturmaTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1174),
                            RolTanim = 0,
                            Silindi = false,
                            Soyad = "Sunal"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Tarık",
                            Aktif = true,
                            GuncellemeTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1177),
                            KullaniciKodu = "Tarık",
                            KullaniciSifre = "asd",
                            MailBildirim = false,
                            OlusturanKullanici = "Tarık",
                            OlusturanKullaniciId = 3,
                            OlusturmaTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1177),
                            RolTanim = 0,
                            Silindi = false,
                            Soyad = "Akan"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Filiz",
                            Aktif = true,
                            GuncellemeTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1179),
                            KullaniciKodu = "Filiz",
                            KullaniciSifre = "321",
                            MailBildirim = false,
                            OlusturanKullanici = "Filiz",
                            OlusturanKullaniciId = 4,
                            OlusturmaTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1179),
                            RolTanim = 0,
                            Silindi = false,
                            Soyad = "Akın"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Türkan",
                            Aktif = true,
                            GuncellemeTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1182),
                            KullaniciKodu = "Türkan",
                            KullaniciSifre = "qwe",
                            MailBildirim = false,
                            OlusturanKullanici = "Türkan",
                            OlusturanKullaniciId = 5,
                            OlusturmaTarihi = new DateTime(2023, 4, 28, 14, 56, 51, 770, DateTimeKind.Local).AddTicks(1181),
                            RolTanim = 0,
                            Silindi = false,
                            Soyad = "Şoray"
                        });
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.MailParametreleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSLKullan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("SmtpAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MailParametreleri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.MalzemeTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MalzemeTip");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriSinifId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriSinifId");

                    b.ToTable("Musteri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.MusteriKisitlama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("IslemAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Kisitlama")
                        .HasColumnType("bit");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId")
                        .IsUnique();

                    b.ToTable("MusteriKisitlama");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.MusteriSinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MusteriSinif");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.MusteriTemsilcisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("MusteriTemsilcisi");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Tedarikci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tedarikci");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.UretimDurus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("DurusSuresi")
                        .HasColumnType("int");

                    b.Property<int>("DurusTipId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("UretimEmriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DurusTipId");

                    b.HasIndex("UretimEmriId");

                    b.ToTable("UretimDurus");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.UretimEmri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuncelleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IsEmriTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("ToplamDurusSuresi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UretimBaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UretimDurum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UretimTamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsId")
                        .IsUnique();

                    b.ToTable("UretimEmri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Ajanda", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.Musteri", "Musteri")
                        .WithMany("Ajandalar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.DepoEnvanter", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.Depo", "Depo")
                        .WithMany("DepoEnvanterler")
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P011_IsTakip.Entities.Classes.DepoRaf", "DepoRaf")
                        .WithMany("DepoEnvanterler")
                        .HasForeignKey("DepoRafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P011_IsTakip.Entities.Classes.Kalinlik", "Kalinlik")
                        .WithMany("DepoEnvanterler")
                        .HasForeignKey("KalinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P011_IsTakip.Entities.Classes.MalzemeTip", "MalzemeTip")
                        .WithMany("DepoEnvanterler")
                        .HasForeignKey("MalzemeTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P011_IsTakip.Entities.Classes.Musteri", "Musteri")
                        .WithMany("DepoEnvanterler")
                        .HasForeignKey("MusteriId");

                    b.Navigation("Depo");

                    b.Navigation("DepoRaf");

                    b.Navigation("Kalinlik");

                    b.Navigation("MalzemeTip");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Is", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.Kalinlik", "Kalinlik")
                        .WithMany("Isler")
                        .HasForeignKey("KalinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P011_IsTakip.Entities.Classes.MalzemeTip", "MalzemeTip")
                        .WithMany("Isler")
                        .HasForeignKey("MalzemeTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P011_IsTakip.Entities.Classes.Musteri", "Musteri")
                        .WithMany("Isler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalinlik");

                    b.Navigation("MalzemeTip");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.IsDosya", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.Is", "Is")
                        .WithOne("IsDosya")
                        .HasForeignKey("P011_IsTakip.Entities.Classes.IsDosya", "IsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Is");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Kullanici", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.Musteri", "Musteri")
                        .WithOne("Kullanici")
                        .HasForeignKey("P011_IsTakip.Entities.Classes.Kullanici", "MusteriId");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Musteri", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.MusteriSinif", "MusteriSinif")
                        .WithMany("Musteriler")
                        .HasForeignKey("MusteriSinifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusteriSinif");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.MusteriKisitlama", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.Musteri", "Musteri")
                        .WithOne("MusteriKisitlama")
                        .HasForeignKey("P011_IsTakip.Entities.Classes.MusteriKisitlama", "MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.MusteriTemsilcisi", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.Musteri", "Musteri")
                        .WithMany("MusteriTemsilciler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.UretimDurus", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.DurusTip", "DurusTip")
                        .WithMany("UretimDuruslari")
                        .HasForeignKey("DurusTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P011_IsTakip.Entities.Classes.UretimEmri", "UretimEmri")
                        .WithMany("UretimDuruslari")
                        .HasForeignKey("UretimEmriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DurusTip");

                    b.Navigation("UretimEmri");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.UretimEmri", b =>
                {
                    b.HasOne("P011_IsTakip.Entities.Classes.Is", "Is")
                        .WithOne("UretimEmri")
                        .HasForeignKey("P011_IsTakip.Entities.Classes.UretimEmri", "IsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Is");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Depo", b =>
                {
                    b.Navigation("DepoEnvanterler");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.DepoRaf", b =>
                {
                    b.Navigation("DepoEnvanterler");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.DurusTip", b =>
                {
                    b.Navigation("UretimDuruslari");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Is", b =>
                {
                    b.Navigation("IsDosya")
                        .IsRequired();

                    b.Navigation("UretimEmri")
                        .IsRequired();
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Kalinlik", b =>
                {
                    b.Navigation("DepoEnvanterler");

                    b.Navigation("Isler");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.MalzemeTip", b =>
                {
                    b.Navigation("DepoEnvanterler");

                    b.Navigation("Isler");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.Musteri", b =>
                {
                    b.Navigation("Ajandalar");

                    b.Navigation("DepoEnvanterler");

                    b.Navigation("Isler");

                    b.Navigation("Kullanici");

                    b.Navigation("MusteriKisitlama")
                        .IsRequired();

                    b.Navigation("MusteriTemsilciler");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.MusteriSinif", b =>
                {
                    b.Navigation("Musteriler");
                });

            modelBuilder.Entity("P011_IsTakip.Entities.Classes.UretimEmri", b =>
                {
                    b.Navigation("UretimDuruslari");
                });
#pragma warning restore 612, 618
        }
    }
}
